CREATE SCHEMA CATTLECO;
USE CATTLECO;

CREATE TABLE CATTLECO.OWNER (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
age INT NOT NULL);


CREATE TABLE CATTLECO.TREATMENT (
  medicationid BIGINT AUTO_INCREMENT PRIMARY KEY,
  medicationdesc VARCHAR(255) NOT NULL,
  medicationsupplierid INT NOT NULL,
  withdrawalperiod INT NOT NULL,
  medicationtypeid INT NOT NULL,
  batchnumber VARCHAR(255) NOT NULL
);
